using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;


namespace RefreshCache.Packager
{


    /// <summary>
    /// A single changelog entry for a specific version. Each package
    /// version that is released should add a new changelog entry to
    /// specify all the changes that were made between the last version
    /// and this new version. Old version changelogs should remain so
    /// that the user can see all the changes made if they are going to
    /// be skipping version numbers.
    /// </summary>
    public class PackageChangelog
    {
        #region Properties

        /// <summary>
        /// The version number that identifies what these changes pertain
        /// to.
        /// </summary>
        public PackageVersion Version { get; set; }

        /// <summary>
        /// A description of all the changes made in this version. Currently
        /// this is a plain text description and will be wrapped in a &lt;pre&gt;
        /// tag when displayed to the user. Later on the display method will
        /// detect HTML tags and allow for simple formatting, such as bullet
        /// points and hyperlinks.
        /// </summary>
        public String Description { get; set; }

        #endregion


        #region Constructors

        /// <summary>
        /// Create a new changelog instance. The instance is empty and
        /// must be populated by the caller before general use.
        /// </summary>
        public PackageChangelog()
        {
            Version = new PackageVersion("1.0.0");
            Description = String.Empty;
        }


        /// <summary>
        /// Create a new instance of the PackageChangelog class that is
        /// populated by the contents of the XmlNode.
        /// </summary>
        /// <param name="node">A XmlNode that was generated by a previous call to the Save() method.</param>
        public PackageChangelog(XmlNode node)
        {
            Version = new PackageVersion(node.Attributes["Version"].Value);
            Description = node.InnerText;
        }

        #endregion


        /// <summary>
        /// Save this Changelog object as a XmlNode that can be later used to
        /// re-instantiate this Changelog entry.
        /// </summary>
        /// <param name="doc">The XmlDocument that will own this node.</param>
        /// <param name="isExport">Specifies if this Save operation is for a final export or not.</param>
        /// <returns>A new XmlNode object that identifies the properties of this instance.</returns>
        public XmlNode Save(XmlDocument doc, Boolean isExport)
        {
            XmlNode node = doc.CreateElement("Changelog");
            XmlAttribute attrib;


            attrib = doc.CreateAttribute("Version");
            attrib.Value = Version.ToString();
            node.Attributes.Append(attrib);

            node.InnerText = Description;

            return node;
        }
    }
}
